### ISSUE TITLE
cant open the docker image

### ISSUE THREAD

**Issue by der-lu** [AndrewBestbier/reMarkableWeb#2]
Hey. I really like your work. Unfortunately, I can't open the docker image. I get the following error:

WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
exec /usr/local/bin/docker-entrypoint.sh: exec format error

How can I open the App without docker?

Greetings 
Luigi

**Comment by abestbier-cais** [comment]
I tried 

```
 docker buildx build --platform linux/amd64,linux/arm64 --tag=andrewbestbier/remarkable-web --push .
```

Can you try now?

**Comment by der-lu** [comment]
Hey. Now I tried

```
docker run - it andrewbestbier/remarkable-web
```


Give me the following output without doing anything else

```
Listening to Port 3000
```


Or am I doing something wrong?


Greetings
derlu

**Comment by abestbier-cais** [comment]
Hey that is looking better. So the app runs on port 3000 within the container itself and you have it running. Now to actually access it yourself

Run the following command:

```
docker run -p 1111:3000 andrewbestbier/remarkable-web
```

Here we map TCP port 1111 in the container to port 3000 on the Docker host. You can choose whatever you wish. If you then go to localhost:1111, you should see the app 😄

**Comment by der-lu** [comment]
amazing. thx, works great

**Comment by abestbier-cais** [comment]
Great. You could also just run it locally with `npm run dev`. Good luck and let me know what other features would be helpful
